import { DownloadCategory } from "./types";

export const downloadCategories: DownloadCategory[] = [
  {
    id: "1",
    name: "Trading Guides",
    description: "Comprehensive guides for cryptocurrency trading",
    downloads: [
      {
        id: "1-1",
        title: "Beginner's Guide to Margin Trading",
        description:
          "A complete guide for beginners to understand margin trading basics",
        category: "Trading Guides",
        fileUrl: "/downloads/beginners-guide.pdf",
        fileType: "PDF",
        fileSize: "2.4 MB",
        downloadCount: 1250,
        createdAt: new Date("2024-01-15"),
        updatedAt: new Date("2024-01-15"),
      },
      {
        id: "1-2",
        title: "Advanced Trading Strategies",
        description: "Learn advanced trading techniques and strategies",
        category: "Trading Guides",
        fileUrl: "/downloads/advanced-trading.pdf",
        fileType: "PDF",
        fileSize: "3.1 MB",
        downloadCount: 850,
        createdAt: new Date("2024-01-20"),
        updatedAt: new Date("2024-02-01"),
      },
      {
        id: "1-3",
        title: "Risk Management Handbook",
        description: "Essential risk management strategies for traders",
        category: "Trading Guides",
        fileUrl: "/downloads/risk-management.pdf",
        fileType: "PDF",
        fileSize: "1.8 MB",
        downloadCount: 975,
        createdAt: new Date("2024-02-01"),
        updatedAt: new Date("2024-02-01"),
      },
    ],
  },
  {
    id: "2",
    name: "Technical Analysis",
    description: "Resources for technical analysis and chart patterns",
    downloads: [
      {
        id: "2-1",
        title: "Chart Pattern Recognition",
        description: "Learn to identify and trade common chart patterns",
        category: "Technical Analysis",
        fileUrl: "/downloads/chart-patterns.pdf",
        fileType: "PDF",
        fileSize: "4.2 MB",
        downloadCount: 2100,
        createdAt: new Date("2024-01-10"),
        updatedAt: new Date("2024-01-25"),
      },
      {
        id: "2-2",
        title: "Technical Indicators Guide",
        description: "Comprehensive guide to technical indicators",
        category: "Technical Analysis",
        fileUrl: "/downloads/indicators.pdf",
        fileType: "PDF",
        fileSize: "5.5 MB",
        downloadCount: 1800,
        createdAt: new Date("2024-01-12"),
        updatedAt: new Date("2024-02-01"),
      },
      {
        id: "2-3",
        title: "Candlestick Patterns",
        description: "Master Japanese candlestick patterns",
        category: "Technical Analysis",
        fileUrl: "/downloads/candlesticks.pdf",
        fileType: "PDF",
        fileSize: "3.8 MB",
        downloadCount: 1650,
        createdAt: new Date("2024-01-18"),
        updatedAt: new Date("2024-01-18"),
      },
    ],
  },
  {
    id: "3",
    name: "Market Research",
    description: "Market analysis and research reports",
    downloads: [
      {
        id: "3-1",
        title: "Crypto Market Overview 2024",
        description: "Comprehensive analysis of the cryptocurrency market",
        category: "Market Research",
        fileUrl: "/downloads/market-overview-2024.pdf",
        fileType: "PDF",
        fileSize: "6.2 MB",
        downloadCount: 3200,
        createdAt: new Date("2024-01-05"),
        updatedAt: new Date("2024-02-01"),
      },
      {
        id: "3-2",
        title: "DeFi Sector Analysis",
        description: "In-depth analysis of the DeFi sector",
        category: "Market Research",
        fileUrl: "/downloads/defi-analysis.pdf",
        fileType: "PDF",
        fileSize: "4.7 MB",
        downloadCount: 1450,
        createdAt: new Date("2024-01-22"),
        updatedAt: new Date("2024-01-22"),
      },
    ],
  },
  {
    id: "4",
    name: "Tools and Templates",
    description: "Trading tools, calculators, and templates",
    downloads: [
      {
        id: "4-1",
        title: "Trading Journal Template",
        description: "Excel template for tracking trades",
        category: "Tools and Templates",
        fileUrl: "/downloads/trading-journal.xlsx",
        fileType: "XLSX",
        fileSize: "245 KB",
        downloadCount: 4500,
        createdAt: new Date("2024-01-08"),
        updatedAt: new Date("2024-01-08"),
      },
      {
        id: "4-2",
        title: "Position Size Calculator",
        description: "Calculate optimal position sizes",
        category: "Tools and Templates",
        fileUrl: "/downloads/position-calculator.xlsx",
        fileType: "XLSX",
        fileSize: "180 KB",
        downloadCount: 3800,
        createdAt: new Date("2024-01-15"),
        updatedAt: new Date("2024-02-01"),
      },
      {
        id: "4-3",
        title: "Risk Management Calculator",
        description: "Calculate risk and potential returns",
        category: "Tools and Templates",
        fileUrl: "/downloads/risk-calculator.xlsx",
        fileType: "XLSX",
        fileSize: "210 KB",
        downloadCount: 2900,
        createdAt: new Date("2024-01-20"),
        updatedAt: new Date("2024-01-20"),
      },
    ],
  },
  {
    id: "5",
    name: "Educational Videos",
    description: "Video tutorials and educational content",
    downloads: [
      {
        id: "5-1",
        title: "Trading Basics Course",
        description: "Video series covering trading fundamentals",
        category: "Educational Videos",
        fileUrl: "/downloads/trading-basics.zip",
        fileType: "ZIP",
        fileSize: "1.2 GB",
        downloadCount: 980,
        createdAt: new Date("2024-01-25"),
        updatedAt: new Date("2024-02-01"),
      },
      {
        id: "5-2",
        title: "Technical Analysis Masterclass",
        description: "Complete video course on technical analysis",
        category: "Educational Videos",
        fileUrl: "/downloads/ta-masterclass.zip",
        fileType: "ZIP",
        fileSize: "2.1 GB",
        downloadCount: 750,
        createdAt: new Date("2024-01-28"),
        updatedAt: new Date("2024-01-28"),
      },
    ],
  },
];
