packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@tanstack/react-query": ^5.66.5
  "@trpc/client": ^11.0.0-rc.772
  "@trpc/tanstack-react-query": ^11.0.0-rc.772
  "@trpc/server": ^11.0.0-rc.772
  "@types/escape-html": "^1.0.2"
  "copyfiles": "^2.4.1"
  "graphql": "^16.8.2"
  "next-sitemap": "^4.2.3"
  "pg": "^8.13.3"
  "prism-react-renderer": "^2.3.1"
  "null-loader": "^4.0.1"
  "@eslint/eslintrc": "^3.2.0"

  superjson: "2.2.2"
  sharp: "0.32.6"
  geist: "^1.3.1"
  eslint: ^9.19.0
  prettier: ^3.4.2
  tailwindcss: ^3.4.14
  typescript: ^5.7.3
  zod: ^3.24.1
  dotenv-cli: ^8.0.0

catalogs:
  react18:
    react: 18.3.1
    react-dom: 18.3.1
    "@types/node": ^22.10.10
    "@types/react": ^18.3.11
    "@types/react-dom": ^18.3.1
  react19:
    react: "^19.0.0"
    react-dom: "^19.0.0"
    eslint: ^9.16.0
    "@types/node": ^22.10.10
    "@types/react": "19.0.7"
    "@types/react-dom": "19.0.3"
  next14:
    next: "^14.2.23"
  next15:
    next: "^15.1.5"
